<div id="footer">
<div id="footnav"> 
<p><a href="/">Digital Collections Home</a> | <a href="/fairuse/index.html">Fair Use Policy</a> | <a href="/help/index.html">Help and Feedback</a> | 
<a href="https://www.uc.edu/about/policies/non-discrimination.html" target="_blank">Notice of Non-Discrimination</a>
</p>
  <p id="footnavb"><a target="_self" href="http://www.libraries.uc.edu/">University of Cincinnati Libraries</a></p>
  <p id="footnavb"><a target="_self" href="http://www.ipo.uc.edu/index.cfm?fuseaction=home.infringement">Copyright
 Information</a> &copy;<a href="http://www.uc.edu/"> University of Cincinnati</a>, 2010
<br/>
</p>

</div>
</div>


<div class="addft"> 
<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-8099459-5");
pageTracker._trackPageview();
} catch(err) {}</script>
</div>
