<!--begin header-->

<div id="headerwrap">
<img src="/oesper/images/oesper_head.jpg" alt="main" usemap="#Map"
width="758" border="0" vspace="0" hspace="0" height="96" align="middle" style="margin: 0px auto 0px auto; width: 758px;"/>
<map name="Map" id="Map">
  <area shape="rect" coords="615,11,752,68" href="http://www.uc.edu/"
target="_blank" alt="UC Home Page" title="UC Home Page"/>
  <area shape="rect" coords="21,57,193,90"
href="http://libraries.uc.edu/" alt="UC Libraries Home Page" title="UC Libraries Home Page"/>
  <area shape="rect" coords="28,18,181,35"
href="/" alt="UC Libraries Digital Collections Home Page" title="UC Libraries Digital Collections Home Page"/>
  <area shape="rect" coords="369,0,586,96"
href="/oesper/" alt="The Oesper Collections in the History of Chemistry" title="The Oesper Collections in the History of Chemistry"/>
</map>

<!--end header-->
