<!--begin header-->
 <div id="headerwrap"><div id="headertopleft"><!--<img src="../images/catlin_small.jpg" width="360" height="70" border="0" hspace="0" vspace="0">-->
<script type="text/javascript" src="../scripts/random.js">
</script>
  </div>
<div id="headertopright">
<img src="../images/logo_headright.jpg" alt="ul image" width="420" height="70" border="0"  hspace="0" vspace="0" usemap="#headmap" />
  <map name="headmap" id="headmap">
  <area shape="rect" coords="334,6,444,66" href="http://www.uc.edu" target="_blank" title="UC Home Page" alt="UC Home Page" />
  <area shape="rect" coords="48,6,331,47" href="http://www.libraries.uc.edu" target="_blank" alt="University of Cincinnati Libraries Home Page" title="University of Cincinnati Libraries Home Page"/>
  </map>
</div>
</div>
