<!--begin header-->
<div id="header">
<script type="text/javascript" src="/scripts/random_main.js"></script>
<map name="Map" id="Map">
  <area shape="rect" coords="615,0,752,96" href="http://www.uc.edu/" 
target="_blank" alt="UC Home Page" title="UC Home Page">
  <area shape="rect" coords="0,49,193,96" 
href="http://libraries.uc.edu/" alt="UC Libraries Home Page" title="UC Libraries Home Page">
  <area shape="rect" coords="0,0,193,48" 
href="../" alt="UC Libraries Digital Collections Home Page" title="UC Libraries Digital Collections Home Page">
</map>
</div>
<!-- end header -->
