<!--begin header-->

<div id="headerwrap">

<div id="headertopleft">
<img src="/images/oesper_topleft.jpg" width="360" height="70" border="0" hspace="0" vspace="0" title="Plaque at entrance to Apparatus Museum" alt="Plaque at entrance to Apparatus Museum"/>
 </div>

<div id="headertopright">
<img src="/images/logo_headright.jpg" title="University Libraries and UC logos" alt="University Libraries and UC logos" width="420" height="70" border="0"  hspace="0" vspace="0" usemap="#headmap" />
  <map name="headmap" id="headmap">
  <area shape="rect" coords="334,6,444,66" href="http://www.uc.edu" target="_blank" alt="UC Home Page" title="UC Home Page" />
  <area shape="rect" coords="48,6,331,47" href="http://www.libraries.uc.edu" target="_blank" alt="University Libraries Home Page" title="University Libraries Home Page" />
  </map>
</div>

</div>

<!--end header-->
