<br clear="all"/>
<div style="width: 40%; margin: 10px 0px 0px 10px; float: left;">
<a href="/oesper/museum/displays.html"><img src="/images/arrowleft.gif" align="top" vspace="0" hspace="2" width="20" height="18" alt="Displays" title="Displays" border="0"/></a><a href="/oesper/museum/displays.html"><b>Displays</b></a>
</div>
<div style="width: 40%; margin: 10px 10px 0px 0px; float: right;">
<a href="/oesper/museum/virtual_tour/index.html"><img src="/images/arrowleft.gif" align="top" vspace="0" hspace="2" width="20" height="18" alt="Museum Virtual Tour" title="Museum Virtual Tour" border="0"/></a><a href="/oesper/museum/virtual_tour/index.html"><b>Museum Virtual Tour</b></a>
</div>
