<div id="qlwrap" style="background-color: transparent;"> 
<div class="qliw" style="background-color: transparent;">
   <h2>Quicklinks</h2>
 <ul>
  <li id="intro"><a href="/oesper/index.asp">Introduction</a></li>
  <li id="history">&nbsp;&mdash;&nbsp;<a href="/oesper/history/index.asp">History</a></li>
  <li id="credits">&nbsp;&mdash;&nbsp;<a href="/oesper/credits/index.asp">Credits</a></li>
  <li id="museum"><a href="/oesper/museum/index.asp">Apparatus Museum</a></li>
  <li id="tour">&nbsp;&mdash;&nbsp;<a href="/oesper/museum/virtual_tour/index.asp">Museum Virtual Tour</a></li>
  <li id="lab">&nbsp;&mdash;&nbsp;<a href="/oesper/museum/virtual_tour/lab/index.asp">Laboratory Virtual Tour</a></li>
  <li id="displays">&nbsp;&mdash;&nbsp;<a href="/oesper/museum/displays.asp">Displays</a></li>
  <li id="portraits"><a href="/oesper/portraits/index.asp">Portraits &amp; Prints</a></li>
  <li id="books"><a href="/oesper/books/index.asp">Books & Journals</a></li>
  <li id="notes"><a href="/oesper/museum-notes/index.asp">Museum Notes</a></li>
  <li id="indices"><a href="/oesper/indices/index.asp">Indices</a></li>
</ul>
</div>

<br clear="all"/>
<div style="width:100%; margin: 0px; padding: 2px; background-color: transparent;">

<h2>
Highlighted Item:
</h2>
<a href="/oesper/museum/virtual_tour/lab/index.asp"><img src="/oesper/images/lab_thumbnail.jpg" alt="Reconstruction of early 20th-century chemical laboratory" title="Reconstruction of early 20th-century chemical laboratory" width="185" height="99" vspace="0" hspace="0" border="0" style="width: 185px; margin: -8px auto 0px auto; padding: 0px 0px 0px 5px; border: 0px;"></a>New! A 360&deg; <a href="/oesper/museum/virtual_tour/lab/index.asp">Virtual Tour</a> of a reconstruction of an early 20th-century (circa 1900-1910) chemical laboratory
<br/>&nbsp;
<br/>&nbsp;
<br/>&nbsp;
</div>

</div>
