   <!-- Begin Quicklinks -->
<div style="background-color: #FFFFFF; 
	position: relative; 
	width: 20%; 
	max-width: 294px; 
	float: left; 
	padding: 0px; 
	border: 0px; 
	margin: 0px 20px 0px 0px; 
	height: auto; 
	font-size: 100%;
	text-align:left;
	clear: none;
	padding:5px 3px 0px 2px;" >

<div class="qliw" style="width: 100%; max-width: 294px;">
   <h2>Quicklinks</h2>
  <ul>
<li><a href="http://digital.libraries.uc.edu/luna/servlet/allCollections">UC Libraries Digital Collections (Luna)</a></li>
  <li><a href="http://drc.libraries.uc.edu">UC Digital Resource Commons (OhioLINK)</a></li>
  <li><a href="/projects/index.html">Digital Collections list</a></li>
<li><a href="/exhibits/index.html">Exhibits</a></li>
  <li><a href="/">Digital Collections home</a></li>
  <li><a href="http://www.libraries.uc.edu/">UC Libraries home</a></li>
  <li><a href="/help/index.html">Help &amp; Feedback</a></li>
</ul>
</div>

<br clear="all"/>
<div style="width:100%; margin: 0px auto 0px auto; padding: 10px 0px 0px 0px;">
<center><a href="http://www.surveymonkey.com/s/2KGJVPK"><img src="survey.gif" border="0" width="200" height="38" alt="Please take our survey!" title="Please take our survey!" align="middle"/></a></center>
</div>

</div>

<!--end quicklinks-->
