<div id="qlwrap" style="width: 275px;"> 

<div class="qliw" style="width: 100%;">
   <h2>Quicklinks</h2>
  <ul>
<li><a href="http://digital.libraries.uc.edu/luna/servlet/allCollections">UC Libraries Digital Collections (Luna)</a></li>
  <li><a href="http://drc.libraries.uc.edu">UC Digital Resource Commons (OhioLINK)</a></li>
  <li><a href="/projects/index.html">Digital Collections list</a></li>
<li><a href="/exhibits/index.html">Exhibits</a></li>
  <li><a href="/">Digital Collections home</a></li>
  <li><a href="http://www.libraries.uc.edu/">UC Libraries home</a></li>
  <li><a href="/help/index.html">Help &amp; Feedback</a></li>
</ul>


</div>

<br clear="all"/>
<br clear="all"/>

<img src="sabin-nixon.jpg" align="absbottom" height="203" width="267" alt="Dr. Sabin receives the National Medial of Science from President Nixon, 1970" title="Dr. Sabin receives the National Medial of Science from President Nixon, 1970" />

</div>