<div id="qlwrap"> 
<div class="qliw">
   <h2>Quicklinks</h2>
 <ul>
  <li id="intro"><a href="/oesper/index.asp">Introduction</a></li>
  <li id="history">&nbsp;&mdash;&nbsp;<a href="/oesper/history/index.asp">History</a></li>
  <li id="credits">&nbsp;&mdash;&nbsp;<a href="/oesper/credits/index.asp">Credits</a></li>
  <li id="museum"><a href="/oesper/museum/index.asp">Apparatus Museum</a></li>
  <li id="tour">&nbsp;&mdash;&nbsp;<a href="/oesper/museum/virtual_tour/index.asp">Virtual Tour</a></li>
  <li id="lab">&nbsp;&mdash;&nbsp;<a href="/oesper/museum/virtual_tour/lab/index.asp">Laboratory Virtual Tour</a></li>
  <li id="displays">&nbsp;&mdash;&nbsp;<a href="/oesper/museum/displays.asp">Displays</a></li>
  <li id="portraits"><a href="/oesper/portraits/index.asp">Portraits &amp; Prints</a></li>
  <li id="books"><a href="/oesper/books/index.asp">Books & Journals</a></li>
  <li id="newBooks">&nbsp;&mdash;&nbsp;<a href="http://guides.libraries.uc.edu/oespernewbooks">New Books in Oesper</a></li>
  <li id="notes"><a href="/oesper/museum-notes/index.asp">Museum Notes</a></li>
  <li id="indices"><a href="/oesper/indices/index.asp">Indices</a></li>
</ul>
</div>
</div>
