            <style>
              ul#nav {
                width: 175px;
                margin-left: -50px;
                font-family: 'Helvetica Nue', Helvetica, Arial, san-serif;
                font-weight: bold;
              }
              ul#nav li {
                list-style: none;
                border: solid 1px black;
                text-align: center;
                margin: 15px;
                display: block;
                text-decoration: none;
                height: auto;
                padding: 5px;
                background: #e4efc0; /* Old browsers */
                background: -moz-linear-gradient(top,  #e4efc0 0%, #abbd73 100%); /* FF3.6+ */
                background: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#e4efc0), color-stop(100%,#abbd73)); /* Chrome,Safari4+ */
                background: -webkit-linear-gradient(top,  #e4efc0 0%,#abbd73 100%); /* Chrome10+,Safari5.1+ */
                background: -o-linear-gradient(top,  #e4efc0 0%,#abbd73 100%); /* Opera 11.10+ */
                background: -ms-linear-gradient(top,  #e4efc0 0%,#abbd73 100%); /* IE10+ */
                background: linear-gradient(to bottom,  #e4efc0 0%,#abbd73 100%); /* W3C */
                filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#e4efc0', endColorstr='#abbd73',GradientType=0 ); /* IE6-9 */
              }
              ul#nav li a {
                color: black;
                text-decoration: none;
              }
            </style>
            <ul id="nav">
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/">Home</a></li>
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/articles/articles.html">Articles/Books</a></li>
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/photos/photos.html">Photos</a></li>
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/correspond/correspond.html">Correspondence</a></li>
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/timeline/timeline.html">Timeline</a></li>
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/patents/patents.html">Patents</a></li>
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/bibliography/biblio.html">Bibliography</a></li>
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/works/works.html">Other works</a></li>
              <li><a href="http://digital.libraries.uc.edu/exhibits/ceas/strauss/other/other.html">Web sites</a></li>
          </ul>
