<?php

 echo "<div id=\"subnav\"><a href=\"http://digital.libraries.uc.edu\">Digital Collections Home</a> | <a href=\"http://digital.libraries.uc.edu/newsrecord/\">News Record</a>";
		
 echo "<div id=\"subnavb\">   <a href=\"http://www.libraries.uc.edu\">Libraries Home</a> | <a href=\"http://www.libraries.uc.edu/libraries/chem-bio/\">Chemistry-Biology Library</a> | <a href=\"http://www.che.uc.edu/\" target=\"_blank\">Department of Chemistry</a>
</div>
</div>";

//<!-- end header -->

echo "</div>";


?>
