  <!--begin subnavigation -->

<div id="nav">
<div class="c50l" style="width: 99.666%;">
  <!--Insert your subtemplate content here-->

  <script type="text/javascript">
   CallbreadCrumbs ("UC Libraries Digital Collections");
		</script>


<div id="subnavb">   

<script type="text/javascript">
    LinksTopRight();
</script>
</div>

</div>


<!--
<script>
YAHOO.util.Event.onDOMReady(function () {

	//	Instantiate a MenuBar, passing in the id of the HTML element 
	//	representing the MenuBar.

    var oMenuBar = new YAHOO.widget.MenuBar("ulmenubar");
    

    // Render the MenuBar instance
    
    oMenuBar.render();
    
});
</script>
-->
</div>
  <!--end subnavigation -->
