<a name="tbs" id="tbs"></a>

  <div id="tabwrap">
<ul id="menu">
<li id="nav1"><a href="/oesper/index.html">Introduction</a></li>
<!-- nav2 was for Virtual Tour-->
<li id="nav3"> <a href="/oesper/museum/index.html">Apparatus Museum</a></li>
<li id="nav4"><a href="/oesper/portraits/index.html">Portraits &amp; Prints</a></li>
<li id="nav5"><a href="/oesper/books/index.html">Books &amp; Journals</a></li>
<li id="nav7"><a href="/oesper/museum-notes/index.html">Museum Notes</a></li>
<li id="nav8"><a href="/oesper/museum-booklets/index.html">Museum Booklets</a></li>
<li id="nav6"><a href="/oesper/indices/index.html">Indices</a></li>
</ul>

<div class="nsdisplay"><hr /></div>
  </div>
