<a name="tbs" id="tbs"></a>
 
  <div id="tabwrap">
<!--<ul id="menu" style="margin-bottom: -10px; padding-bottom: 0px;border:0px solid #CCC;">-->
<ul id="menu">
<li id="nav0"><a href="/oesper/index.asp">Oesper Home</a></li>
<li id="nav1"><a href="/oesper/introduction/index.asp">Introduction</a></li>
<li id="nav3"> <a href="/oesper/museum/index.asp">Museum</a></li>
<li id="nav4"><a href="/oesper/portraits/index.asp">Portraits &amp; Prints</a></li>
<li id="nav5"><a href="/oesper/books/index.asp">Books &amp; Journals</a></li>
<li id="nav8"><a href="/oesper/indices/index.asp">Indices</a></li>
</ul>
<!--
<br clear="all"/>
<div style="text-align: left; width: 5px; height: 10px; float: left; margin: -10px 0px 0px 60px; padding: 0px; border-left:1px solid #CCC;">
&nbsp;</div>
<div style="text-align: left; width: 5px; height: 10px; float: left; margin: -10px 0px 0px 160px; padding: 0px; border-left:1px solid #CCC;">
&nbsp;</div>

<ul id="menu" style="width: auto; float: left; margin-right: 6px;" >
  <li id="nav6">
<a href="/oesper/introduction/history/index.asp">History</a></li>
  <li id="nav7">
<a href="/oesper/introduction/credits/index.asp">Credits</a></li>
</ul>

<ul id="menu" style="width: auto; float: left;" >
  <li id="nav2"><a href="/oesper/museum/virtual_tour/index.asp">Virtual Tour</a></li>
  <li id="nav9"><a href="/oesper/museum/displays/index.asp">Displays</a></li>
</ul>

<div id="menu" style="width:60%; float: left; border: 0px solid #CCC; display: inline; background: transparent;">
&nbsp;&nbsp;&nbsp;
</div>
-->

<div class="nsdisplay"><hr /></div>
  </div>
