<a name="tbs" id="tbs"></a>
 
  <div id="tabwrap">
<ul id="menu">
  <li id="nav1"><a href="/oesper/index.asp">Introduction</a>
  </li>
  <li id="nav2"> <a href="/oesper/virtual_tour/index.asp">Virtual Tour</a> 
  </li>
  <li id="nav3"> <a href="/oesper/museum/index.asp">Apparatus Museum</a> 
  </li>
  <li id="nav4"><a href="/oesper/portraits/index.asp">Portraits &amp; Prints</a>
  </li>
<!--  <li id="nav5"><a href="/oesper/books/index.asp">Books &amp; Journals</a> -->
  <li id="nav5"><a href="/oesper/credits/index.asp">Credits</a>
  </li>
  <li id="nav6"><a href="/oesper/site_index/index.asp">Site Indices</a>
  </li>
</ul>
<div class="nsdisplay"><hr /></div>
   
  </div>
